# Generated by Django 6.0.4 on 2026-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('skills_required', models.TextField(blank=True, help_text='Comma-separated skills', null=True)),
                ('platform', models.CharField(blank=True, help_text='e.g. LinkedIn, Indeed, Glassdoor', max_length=100, null=True)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('embedding', models.TextField(blank=True, help_text='SBERT vector as JSON string', null=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.RemoveField(
            model_name='jobembedding',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobEmbedding',
        ),
    ]
